name: 'Slackapi Changelog Generator'
description: 'Generate Changelog in slack mrkdwn format from conventional commits since latest tag or from a given tag range'
author: peterchanxyz
inputs:
  token:
    description: GitHub Token
    required: true
  tag:
    description: The latest tag (which triggered this job) (only if using latest tag)
    required: false
  fromTag:
    description: The tag from which the changelog is to be determined (only if using tag range)
    required: false
  toTag:
    description: The tag up to which the changelog is to be determined (only if using tag range)
    required: false
  title:
    description: The change log title
    required: false
  slackBotToken:
    description: slack bot token
    required: false
  slackChannelIds:
    description: slack channel id, separate by ','
    required: false
  excludeTypes:
    description: Types to exclude from the Changelog
    required: false
    default: build,docs,other,style
  useGitmojis:
    description: Prepend type headers with their corresponding gitmoji
    required: false
    default: 'true'
  includeInvalidCommits:
    description: Whether to include commits that don't respect the Conventional Commits format
    required: false
    default: 'true'
  reverseOrder:
    description: List commits in reverse order (from newer to older) instead of the default (older to newer).
    required: false
    default: 'false'
outputs:
  payload:
    description: Generated changelog in slack mrkdwn format
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: wind
  color: blue
